[package]
name = "iris_ecma"
authors.workspace = true
categories.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
oxc = { workspace = true, features = ["full"] }
oxc_resolver = { workspace = true }
