[package]
name = "iris_python"
authors.workspace = true
categories.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
ruff = { workspace = true }
iris_low_level_ir = { workspace = true }